server:
  port: "8080"
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "video_db"
redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0
jwt:
  secret: "my_super_secret_key_fanone"
oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com"
  access_key: ""
  secret_key: ""
  bucket: ""
  domain: ""