server:
  port: "8080"
  run_mode: "debug"
  upload_type: "minio"
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "video_db"
redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0
jwt:
  secret: "my_super_secret_key_fanone"
minio:
  endpoint: "127.0.0.1:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "videostorage"
oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com"
  access_key: ""
  secret_key: ""
  bucket: ""
  domain: ""