version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: video_db
    ports:
        - "3306:3306"
    volumes:
        - mysql_data:/var/lib/mysql
    networks:
        - video_net
  redis:
    image: redis:alpine
    container_name: video_redis
    ports:
        - "6379:6379"
    networks:
        - video_net
  app:
    build: .
    container_name: video_app
    ports:
      - "9090:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=video_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    volumes:
      - ./upload:/app/uploads
    networks:
      - video_net
volumes:
    mysql_data:
networks:
    video_net:
